# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufac_id', models.CharField(max_length=60, unique=True)),
                ('manufac_model', models.CharField(blank=True, max_length=60)),
                ('given_name', models.CharField(blank=True, max_length=80)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
