# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HusqAM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batteryPercent', models.SmallIntegerField()),
                ('connected', models.BooleanField()),
                ('lastErrorCode', models.SmallIntegerField()),
                ('lastErrorTimestamp', models.DateTimeField(blank=True, null=True)),
                ('mowerStatus', models.CharField(max_length=80)),
                ('nextStartSource', models.CharField(max_length=80)),
                ('nextStartTimestamp', models.DateTimeField()),
                ('operatingMode', models.CharField(max_length=40)),
                ('storedTimestamp', models.DateTimeField()),
                ('showAsDisconnected', models.BooleanField()),
                ('valueFound', models.BooleanField()),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HusqAM.Robot')),
            ],
            options={
                'verbose_name_plural': 'Status',
                'ordering': ['timestamp'],
            },
        ),
    ]
