# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HusqAM', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='nextStartTimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
