# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('HusqAM', '0003_auto_20180710_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='HusAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hus_login', models.CharField(max_length=60)),
                ('hus_password', models.CharField(max_length=60)),
                ('token_id', models.CharField(blank=True, max_length=60)),
                ('token_provider', models.CharField(blank=True, max_length=60)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
