# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HusqAM', '0004_husaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='anon_id',
            field=models.CharField(blank=True, default=None, help_text="The robot's ID that is used for sharing through a private link.", max_length=10, null=True, unique=True),
        ),
    ]
